### ISSUE TITLE
Patch Pantheon/Elementary

### ISSUE THREAD

**Issue by windowsboy111** [terrapkg/packages#1]
See commits 7452874 and 8f909d1 and their corresponding gh workflows.

# Intention
Add support for [Pantheon/Elementary packages](https://fedoraproject.org/wiki/SIGs/Pantheon) since [upstream Fedora removed them](https://pagure.io/workstation-ostree-config/c/6901df28087794e2fbec1bcd976fd4220db0001d?branch=main).

# Summary
## `pkgconfig`s Missing
- `gala` which depends on mutter
- `wingpanel` which depends on mutter
- `mutter-cluster-10`
- `mutter-cogl-10`
- `mutter-cogl-pango-10`

## Failed to Compile
- [`switchboard-plug-onlineaccounts`](https://github.com/terrapkg/packages/actions/runs/3255485537/jobs/5346850691#step:4:7064) (`camel`?) [upstream](https://src.fedoraproject.org/rpms/switchboard-plug-onlineaccounts/) needs to be patched to support new evolution-data-server version
- [`elementary-calendar`](https://github.com/terrapkg/packages/actions/runs/3255485537/jobs/5346847317#step:4:7201) (wrong `libsoup` version?) [upstream](https://src.fedoraproject.org/rpms/elementary-calculator/) last successful build has no difference with latest failed build

# Tasks
- [x] `elementary-calendar` depends on `evolution-data-server` but latest provides both libsoup 2 and 3 so the 3.44.4 version from terra is used; but another dependency `folks-devel` requires `pkgconfig(libedataserver-1.2) >= 3.38` (provided by latest `evolution-data-server`)
- [x] patch switchboard-plug-onlineaccounts to support new edataserver code (or wait for https://github.com/elementary/switchboard-plug-onlineaccounts/issues/243)
- [x] #2
- [x] `wingpanel` and its dependencies

**Comment by windowsboy111** [comment]
some more packages with issues:
https://github.com/terrapkg/packages/actions/runs/3514696155
