### ISSUE TITLE
[FYRA-283] Paving the road to Terra 39

### ISSUE THREAD

**Issue by lleyton** [terrapkg/packages#696]
# Introduction

This is a general issue for discussion and changes for a Terra 39 release. We have already branched off of Terra 38, bootstrapped the repository, and attempted a mass build of all packages in the repository. We'll also be having discussion in the [Fyra Discord](https://discord.gg/5fdPuxTg5Q) as usual.

# Current notes
- There are currently a large number of failing packages. [Here's a list of them.](https://github.com/terrapkg/packages/files/12385381/failed.txt)
  - Packages that fail to build or don't work as expected by the time Terra 39 is released are at risk of being removed from the repository.
  - See the following mass builds
    - https://github.com/terrapkg/packages/actions/runs/5886308453
    - https://github.com/terrapkg/packages/actions/runs/5886309453
- We're also planning some improvements to our testing workflow, which will probably be implemented prior to or shortly after we release Terra 39. I'll follow up with those in a later comment.
- We're planning to release when Fedora 39 hits GA, but might delay based on the state of the repository.
- A goal of this release is to introduce the `terra-release` package as the preferred method of installing/enabling the Terra repositories. This will allow us to push updates to the .repo files and other config, which may become useful in the future.
  - Manual intervention will most likely be needed for users; we haven't yet figured a clean way to push the release package for users who just added the repo using config-manager.
- If *anyone* has suggestions for improvements or fixes for this upcoming release, we're all (cat)ears :3

# TODOs
- [ ] Fix failing packages
- [ ] Document & implement testing improvements
- [ ] Update documentation to refer to the new release package
- [ ] Go/no-go release and push out announcement

<sub>[FYRA-283](https://linear.app/fyra/issue/FYRA-283/paving-the-road-to-terra-39)</sub>

**Comment by lleyton** [comment]
# Additional Updates

We're also introducing these additional improvements:
- Terra 39 will NOT require users to install RPM Fusion or any other third-party repositories to use any package.
- Go build dependencies won't be shipped within the repository
- Package updates will now happen once every 10 minutes. (excluding nightly)

**Comment by madonuko** [comment]
## Outdated packages
See [Repology](https://repology.org/projects/?inrepo=terra_39&outdated=1)
- [ ] argagg 0.4.7
- [ ] discord-canary 0.0.169
- [ ] discord-canary-openasar 0.0.169
- [ ] discord-ptb 0.0.48
- [ ] discord-ptb-openasar 0.0.48
- [ ] electron 26.2.4
- [ ] elementary-appcenter 7.4.0
- [ ] graalvm 23.0.0
- [ ] groovy 4.0.15
- [ ] limine 5.20230928.2

# Missing packages
See [Repology](https://repology.org/projects/?search=&maintainer=&category=&inrepo=terra_38&notinrepo=terra_39&repos=&families=&repos_newest=&families_newest=)
- [x] anda-mock-configs 3
- [x] anki-bin 2.1.66
- [ ] ayatana-indicator-datetime 23.6.0
- [ ] ayatana-indicator-messages 22.9.0
- [ ] ayatana-indicator-notifications 22.9.0
- [ ] ayatana-indicator-session 22.9.2
- [ ] ayatana-indicator-sound 22.9.2
- [ ] budgie-extras 1.6.0
- [ ] choosenim 0.8.4
- [ ] elementary-icon-theme 7.3.1
- [ ] elementary-onboarding 7.2.0
- [ ] gendesk 1.0.9
- [ ] github-fyshos-fynedesk 0.3.0
- [ ] github-xyproto-gendesk 1.0.9
- [ ] iosevka-fusion-fonts 25.1.1
- [ ] joshuto 0.9.5
- [ ] libayatana-common 0.9.8
- [ ] libusermetrics 1.3.0
- [ ] lomiri 0.1.3
- [ ] lomiri-indicator-network 1.0.0
- [ ] lomiri-session 0.2
- [ ] mate-tweak 22.10.0
- [ ] moby-buildx 0.11.2
- [ ] pqmarble 2.0.0
- [ ] qtmir 0.8.0
- [ ] ruff-python-linter 0.0.291
- [ ] switchboard-plug-networking 2.4.4
- [ ] terra-handbrake 1.6.1
- [ ] unity-scope-home 19.04.20190412
- [ ] unity-shell 7.7.0
- [ ] unityx-shell 1.7.7
- [ ] vala-language-server-nightly 0.48.7
- [ ] vala-lint-nightly 0.1.0
- [ ] vala-panel-appmenu 0.7.6
